### ISSUE TITLE
How to run "php artisan down" from url

### ISSUE THREAD

**Issue by amarathota** [kofoworola/route-commands#3]
hi, could you please provide an example for this one?

**Comment by kofoworola** [comment]
You shouldn't want to be able to run that from the route, even if you do the app would not be "online" to run route commands when you do

**Comment by amarathota** [comment]
ok. Thanks

Is it possible to run **php artisan migrate** from the route? if yes, could you please provide me an example

**Comment by kofoworola** [comment]
Just follow the instructions on the readme, it will help you get started to run migrate
